# Generated by Django 5.1.3 on 2025-02-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='description',
        ),
        migrations.AddField(
            model_name='workflow',
            name='nodes_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
